// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // Provide web configuration. These values are best regenerated
      // using the FlutterFire CLI (`flutterfire configure`) for accuracy.
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
        
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDytsbYd1AaVooqkAo7ISEgj2JkoYZd0NY',
    appId: '1:870506918671:ios:f33d5aa1bf3be4f4fd447a',
    messagingSenderId: '870506918671',
    projectId: 'bullybutton',
    storageBucket: 'bullybutton.firebasestorage.app',
    iosBundleId: 'com.bullybutton.bullybutton',
  );

  // Web configuration. Replace the placeholders by re-running
  // `flutterfire configure` or filling in your Web app credentials.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDytsbYd1AaVooqkAo7ISEgj2JkoYZd0NY',
    authDomain: 'bullybutton.firebaseapp.com',
    projectId: 'bullybutton',
    storageBucket: 'bullybutton.firebasestorage.app',
    messagingSenderId: '870506918671',
    appId: '1:870506918671:web:REPLACE_WITH_WEB_APP_ID',
    measurementId: 'G-REPLACE_WITH_MEASUREMENT_ID',
  );
}
